version: '3.8'

services:
  postgres:
    image: osakagpt/rag_contest_db:latest
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    build:
      context: ./db
      dockerfile: Dockerfile

  app:
    image: osakagpt/rag_contest_app:latest
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    build:
      context: ./app
      dockerfile: Dockerfile

  adminer:
    image: adminer:latest
    restart: always
    ports:
      - "8081:8080"
    depends_on:
      - postgres

volumes:
  postgres_data:
    driver: local
