version: '3.8'

services:
  postgres:
    image: osakagpt/rag_contest_db:latest
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env

  app:
    image: osakagpt/rag_contest_app:latest
    restart: always
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - postgres

  adminer:
    image: adminer:latest
    restart: always
    ports:
      - "8081:8080"
    depends_on:
      - postgres

volumes:
  postgres_data:
    driver: local
